name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Prepare Dockerfile
        run: cp ../Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arvindydv/nxtjob-payment-gateway:latest

      - name: Verify Pushed Image
        run: docker pull arvindydv/nxtjob-payment-gateway:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull arvindydv/nxtjob-payment-gateway:latest
            sudo docker stop nxtjob-payment-gateway || true
            sudo docker rm nxtjob-payment-gateway || true
            sudo docker run -d --name nxtjob-payment-gateway -p 8000:8000 arvindydv/nxtjob-payment-gateway:latest
